/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_myopencvdemo_utils_CVNativeTools */

#ifndef _Included_com_myopencvdemo_utils_CVNativeTools
#define _Included_com_myopencvdemo_utils_CVNativeTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_myopencvdemo_utils_CVNativeTools
 * Method:    caculatePixNumberFromNative
 * Signature: (J)Ljava/util/TreeMap;
 */
JNIEXPORT jobject JNICALL Java_com_myopencvdemo_utils_CVNativeTools_caculatePixNumberFromNative
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
